# Trace and Prioritize

The goal of this notebook is to: 

1. Perform radar tracing to give the "vehicle POV" of surrounding traffic.
2. Estimating anomalies and assign the "anomaly score" onto each vehicle trajectory.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('kalmaned2.csv')

In [7]:
df['Global_Time'] = df['Global_Time'] - df['Global_Time'][0]

In [9]:
df_at_gtime = df[df['Global_Time'] == 5600]

In [12]:
df_at_gtime.head()

,Unnamed: 0,Unnamed: 0.1,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,...,v_Vel,v_Acc,Lane_ID,Preceeding,Following,Space_Hdwy,Time_Hdwy,Vehicle_EKF_Accel,Vehicle_EKF_Theta,Vehicle_EKF_Velocity
56,56,56,1,326,569,5600,51.886,228.567,6451216.040,1873207.671,...,22.33,0.00,5,0,6,0.0,0.0,0.588543,0.001159,21.511094
667,667,667,2,326,634,5600,40.267,236.445,6451229.881,1873210.013,...,11.13,0.00,4,0,10,0.0,0.0,-0.552106,-0.000794,9.963986
1320,1320,1320,3,326,661,5600,25.947,254.485,6451252.688,1873206.893,...,14.06,7.98,3,0,7,0.0,0.0,0.978590,-0.003977,12.131350
2011,2011,2011,4,326,651,5600,15.684,207.725,6451227.703,1873247.845,...,16.24,-0.67,2,0,8,0.0,0.0,0.851395,-0.008498,16.767919
2831,2831,2831,5,326,846,5600,4.643,300.619,6451300.852,1873188.884,...,22.69,0.00,1,0,9,0.0,0.0,-0.739591,0.002148,26.304684

In [15]:
df_at_gtime['Vehicle_ID'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])